// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nautilus.Common {

  /// <summary>Holder for reflection information generated from messages.proto</summary>
  public static partial class MessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for messages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5tZXNzYWdlcy5wcm90bxIQaW52YXJpYW5jZV9wcm90byJSCgRUaWNrEg4K",
            "BnN5bWJvbBgBIAEoCRINCgV2ZW51ZRgCIAEoCRILCgNiaWQYAyABKAESCwoD",
            "YXNrGAQgASgBEhEKCXRpbWVzdGFtcBgFIAEoCSJgCgNCYXISDAoEb3BlbhgB",
            "IAEoARIMCgRoaWdoGAIgASgBEgsKA2xvdxgDIAEoARINCgVjbG9zZRgEIAEo",
            "ARIOCgZ2b2x1bWUYBSABKAUSEQoJdGltZXN0YW1wGAYgASgJIoQBChBCYXJT",
            "cGVjaWZpY2F0aW9uEi4KCXF1b3RlVHlwZRgBIAEoDjIbLmludmFyaWFuY2Vf",
            "cHJvdG8uUXVvdGVUeXBlEjAKCnJlc29sdXRpb24YAiABKA4yHC5pbnZhcmlh",
            "bmNlX3Byb3RvLlJlc29sdXRpb24SDgoGcGVyaW9kGAMgASgFIpkBCglCYXJD",
            "bG9zZWQSDgoGc3ltYm9sGAEgASgJEg0KBXZlbnVlGAIgASgJEjMKB2JhclNw",
            "ZWMYAyABKAsyIi5pbnZhcmlhbmNlX3Byb3RvLkJhclNwZWNpZmljYXRpb24S",
            "IgoDYmFyGAQgASgLMhUuaW52YXJpYW5jZV9wcm90by5CYXISFAoMaXNIaXN0",
            "b3JpY2FsGAUgASgIIjIKEVN1YnNjcmliZVRpY2tEYXRhEg4KBnN5bWJvbBgB",
            "IAEoCRINCgV2ZW51ZRgCIAEoCSI0ChNVbnN1YnNjcmliZVRpY2tEYXRhEg4K",
            "BnN5bWJvbBgBIAEoCRINCgV2ZW51ZRgCIAEoCSJmChBTdWJzY3JpYmVCYXJE",
            "YXRhEg4KBnN5bWJvbBgBIAEoCRINCgV2ZW51ZRgCIAEoCRIzCgdiYXJTcGVj",
            "GAMgASgLMiIuaW52YXJpYW5jZV9wcm90by5CYXJTcGVjaWZpY2F0aW9uImgK",
            "ElVuc3Vic2NyaWJlQmFyRGF0YRIOCgZzeW1ib2wYASABKAkSDQoFdmVudWUY",
            "AiABKAkSMwoHYmFyU3BlYxgDIAEoCzIiLmludmFyaWFuY2VfcHJvdG8uQmFy",
            "U3BlY2lmaWNhdGlvbipBCgpSZXNvbHV0aW9uEggKBFRJQ0sQABIKCgZTRUNP",
            "TkQQARIKCgZNSU5VVEUQAhIICgRIT1VSEAMSBwoDREFZEAQqMAoJUXVvdGVU",
            "eXBlEgcKA0JJRBAAEgcKA0FTSxABEggKBExBU1QQAhIHCgNNSUQQBEISqgIP",
            "TmF1dGlsdXMuQ29tbW9uYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Nautilus.Common.Resolution), typeof(global::Nautilus.Common.QuoteType), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Nautilus.Common.Tick), global::Nautilus.Common.Tick.Parser, new[]{ "Symbol", "Venue", "Bid", "Ask", "Timestamp" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nautilus.Common.Bar), global::Nautilus.Common.Bar.Parser, new[]{ "Open", "High", "Low", "Close", "Volume", "Timestamp" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nautilus.Common.BarSpecification), global::Nautilus.Common.BarSpecification.Parser, new[]{ "QuoteType", "Resolution", "Period" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nautilus.Common.BarClosed), global::Nautilus.Common.BarClosed.Parser, new[]{ "Symbol", "Venue", "BarSpec", "Bar", "IsHistorical" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nautilus.Common.SubscribeTickData), global::Nautilus.Common.SubscribeTickData.Parser, new[]{ "Symbol", "Venue" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nautilus.Common.UnsubscribeTickData), global::Nautilus.Common.UnsubscribeTickData.Parser, new[]{ "Symbol", "Venue" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nautilus.Common.SubscribeBarData), global::Nautilus.Common.SubscribeBarData.Parser, new[]{ "Symbol", "Venue", "BarSpec" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nautilus.Common.UnsubscribeBarData), global::Nautilus.Common.UnsubscribeBarData.Parser, new[]{ "Symbol", "Venue", "BarSpec" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Resolution {
    [pbr::OriginalName("TICK")] Tick = 0,
    [pbr::OriginalName("SECOND")] Second = 1,
    [pbr::OriginalName("MINUTE")] Minute = 2,
    [pbr::OriginalName("HOUR")] Hour = 3,
    [pbr::OriginalName("DAY")] Day = 4,
  }

  public enum QuoteType {
    [pbr::OriginalName("BID")] Bid = 0,
    [pbr::OriginalName("ASK")] Ask = 1,
    [pbr::OriginalName("LAST")] Last = 2,
    [pbr::OriginalName("MID")] Mid = 4,
  }

  #endregion

  #region Messages
  public sealed partial class Tick : pb::IMessage<Tick> {
    private static readonly pb::MessageParser<Tick> _parser = new pb::MessageParser<Tick>(() => new Tick());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Tick> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nautilus.Common.MessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Tick() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Tick(Tick other) : this() {
      symbol_ = other.symbol_;
      venue_ = other.venue_;
      bid_ = other.bid_;
      ask_ = other.ask_;
      timestamp_ = other.timestamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Tick Clone() {
      return new Tick(this);
    }

    /// <summary>Field number for the "symbol" field.</summary>
    public const int SymbolFieldNumber = 1;
    private string symbol_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Symbol {
      get { return symbol_; }
      set {
        symbol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "venue" field.</summary>
    public const int VenueFieldNumber = 2;
    private string venue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Venue {
      get { return venue_; }
      set {
        venue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bid" field.</summary>
    public const int BidFieldNumber = 3;
    private double bid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Bid {
      get { return bid_; }
      set {
        bid_ = value;
      }
    }

    /// <summary>Field number for the "ask" field.</summary>
    public const int AskFieldNumber = 4;
    private double ask_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Ask {
      get { return ask_; }
      set {
        ask_ = value;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 5;
    private string timestamp_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Tick);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Tick other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Symbol != other.Symbol) return false;
      if (Venue != other.Venue) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Bid, other.Bid)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Ask, other.Ask)) return false;
      if (Timestamp != other.Timestamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Symbol.Length != 0) hash ^= Symbol.GetHashCode();
      if (Venue.Length != 0) hash ^= Venue.GetHashCode();
      if (Bid != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Bid);
      if (Ask != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Ask);
      if (Timestamp.Length != 0) hash ^= Timestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Symbol.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Symbol);
      }
      if (Venue.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Venue);
      }
      if (Bid != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Bid);
      }
      if (Ask != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Ask);
      }
      if (Timestamp.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Symbol.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Symbol);
      }
      if (Venue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Venue);
      }
      if (Bid != 0D) {
        size += 1 + 8;
      }
      if (Ask != 0D) {
        size += 1 + 8;
      }
      if (Timestamp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Timestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Tick other) {
      if (other == null) {
        return;
      }
      if (other.Symbol.Length != 0) {
        Symbol = other.Symbol;
      }
      if (other.Venue.Length != 0) {
        Venue = other.Venue;
      }
      if (other.Bid != 0D) {
        Bid = other.Bid;
      }
      if (other.Ask != 0D) {
        Ask = other.Ask;
      }
      if (other.Timestamp.Length != 0) {
        Timestamp = other.Timestamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Symbol = input.ReadString();
            break;
          }
          case 18: {
            Venue = input.ReadString();
            break;
          }
          case 25: {
            Bid = input.ReadDouble();
            break;
          }
          case 33: {
            Ask = input.ReadDouble();
            break;
          }
          case 42: {
            Timestamp = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Bar : pb::IMessage<Bar> {
    private static readonly pb::MessageParser<Bar> _parser = new pb::MessageParser<Bar>(() => new Bar());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Bar> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nautilus.Common.MessagesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Bar() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Bar(Bar other) : this() {
      open_ = other.open_;
      high_ = other.high_;
      low_ = other.low_;
      close_ = other.close_;
      volume_ = other.volume_;
      timestamp_ = other.timestamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Bar Clone() {
      return new Bar(this);
    }

    /// <summary>Field number for the "open" field.</summary>
    public const int OpenFieldNumber = 1;
    private double open_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Open {
      get { return open_; }
      set {
        open_ = value;
      }
    }

    /// <summary>Field number for the "high" field.</summary>
    public const int HighFieldNumber = 2;
    private double high_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double High {
      get { return high_; }
      set {
        high_ = value;
      }
    }

    /// <summary>Field number for the "low" field.</summary>
    public const int LowFieldNumber = 3;
    private double low_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Low {
      get { return low_; }
      set {
        low_ = value;
      }
    }

    /// <summary>Field number for the "close" field.</summary>
    public const int CloseFieldNumber = 4;
    private double close_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Close {
      get { return close_; }
      set {
        close_ = value;
      }
    }

    /// <summary>Field number for the "volume" field.</summary>
    public const int VolumeFieldNumber = 5;
    private int volume_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Volume {
      get { return volume_; }
      set {
        volume_ = value;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 6;
    private string timestamp_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Bar);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Bar other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Open, other.Open)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(High, other.High)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Low, other.Low)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Close, other.Close)) return false;
      if (Volume != other.Volume) return false;
      if (Timestamp != other.Timestamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Open != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Open);
      if (High != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(High);
      if (Low != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Low);
      if (Close != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Close);
      if (Volume != 0) hash ^= Volume.GetHashCode();
      if (Timestamp.Length != 0) hash ^= Timestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Open != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Open);
      }
      if (High != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(High);
      }
      if (Low != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Low);
      }
      if (Close != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Close);
      }
      if (Volume != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Volume);
      }
      if (Timestamp.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Open != 0D) {
        size += 1 + 8;
      }
      if (High != 0D) {
        size += 1 + 8;
      }
      if (Low != 0D) {
        size += 1 + 8;
      }
      if (Close != 0D) {
        size += 1 + 8;
      }
      if (Volume != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Volume);
      }
      if (Timestamp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Timestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Bar other) {
      if (other == null) {
        return;
      }
      if (other.Open != 0D) {
        Open = other.Open;
      }
      if (other.High != 0D) {
        High = other.High;
      }
      if (other.Low != 0D) {
        Low = other.Low;
      }
      if (other.Close != 0D) {
        Close = other.Close;
      }
      if (other.Volume != 0) {
        Volume = other.Volume;
      }
      if (other.Timestamp.Length != 0) {
        Timestamp = other.Timestamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Open = input.ReadDouble();
            break;
          }
          case 17: {
            High = input.ReadDouble();
            break;
          }
          case 25: {
            Low = input.ReadDouble();
            break;
          }
          case 33: {
            Close = input.ReadDouble();
            break;
          }
          case 40: {
            Volume = input.ReadInt32();
            break;
          }
          case 50: {
            Timestamp = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class BarSpecification : pb::IMessage<BarSpecification> {
    private static readonly pb::MessageParser<BarSpecification> _parser = new pb::MessageParser<BarSpecification>(() => new BarSpecification());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BarSpecification> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nautilus.Common.MessagesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BarSpecification() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BarSpecification(BarSpecification other) : this() {
      quoteType_ = other.quoteType_;
      resolution_ = other.resolution_;
      period_ = other.period_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BarSpecification Clone() {
      return new BarSpecification(this);
    }

    /// <summary>Field number for the "quoteType" field.</summary>
    public const int QuoteTypeFieldNumber = 1;
    private global::Nautilus.Common.QuoteType quoteType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Nautilus.Common.QuoteType QuoteType {
      get { return quoteType_; }
      set {
        quoteType_ = value;
      }
    }

    /// <summary>Field number for the "resolution" field.</summary>
    public const int ResolutionFieldNumber = 2;
    private global::Nautilus.Common.Resolution resolution_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Nautilus.Common.Resolution Resolution {
      get { return resolution_; }
      set {
        resolution_ = value;
      }
    }

    /// <summary>Field number for the "period" field.</summary>
    public const int PeriodFieldNumber = 3;
    private int period_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Period {
      get { return period_; }
      set {
        period_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BarSpecification);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BarSpecification other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (QuoteType != other.QuoteType) return false;
      if (Resolution != other.Resolution) return false;
      if (Period != other.Period) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (QuoteType != 0) hash ^= QuoteType.GetHashCode();
      if (Resolution != 0) hash ^= Resolution.GetHashCode();
      if (Period != 0) hash ^= Period.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (QuoteType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) QuoteType);
      }
      if (Resolution != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Resolution);
      }
      if (Period != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Period);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (QuoteType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) QuoteType);
      }
      if (Resolution != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Resolution);
      }
      if (Period != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Period);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BarSpecification other) {
      if (other == null) {
        return;
      }
      if (other.QuoteType != 0) {
        QuoteType = other.QuoteType;
      }
      if (other.Resolution != 0) {
        Resolution = other.Resolution;
      }
      if (other.Period != 0) {
        Period = other.Period;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            quoteType_ = (global::Nautilus.Common.QuoteType) input.ReadEnum();
            break;
          }
          case 16: {
            resolution_ = (global::Nautilus.Common.Resolution) input.ReadEnum();
            break;
          }
          case 24: {
            Period = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class BarClosed : pb::IMessage<BarClosed> {
    private static readonly pb::MessageParser<BarClosed> _parser = new pb::MessageParser<BarClosed>(() => new BarClosed());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BarClosed> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nautilus.Common.MessagesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BarClosed() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BarClosed(BarClosed other) : this() {
      symbol_ = other.symbol_;
      venue_ = other.venue_;
      barSpec_ = other.barSpec_ != null ? other.barSpec_.Clone() : null;
      bar_ = other.bar_ != null ? other.bar_.Clone() : null;
      isHistorical_ = other.isHistorical_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BarClosed Clone() {
      return new BarClosed(this);
    }

    /// <summary>Field number for the "symbol" field.</summary>
    public const int SymbolFieldNumber = 1;
    private string symbol_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Symbol {
      get { return symbol_; }
      set {
        symbol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "venue" field.</summary>
    public const int VenueFieldNumber = 2;
    private string venue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Venue {
      get { return venue_; }
      set {
        venue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "barSpec" field.</summary>
    public const int BarSpecFieldNumber = 3;
    private global::Nautilus.Common.BarSpecification barSpec_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Nautilus.Common.BarSpecification BarSpec {
      get { return barSpec_; }
      set {
        barSpec_ = value;
      }
    }

    /// <summary>Field number for the "bar" field.</summary>
    public const int BarFieldNumber = 4;
    private global::Nautilus.Common.Bar bar_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Nautilus.Common.Bar Bar {
      get { return bar_; }
      set {
        bar_ = value;
      }
    }

    /// <summary>Field number for the "isHistorical" field.</summary>
    public const int IsHistoricalFieldNumber = 5;
    private bool isHistorical_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsHistorical {
      get { return isHistorical_; }
      set {
        isHistorical_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BarClosed);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BarClosed other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Symbol != other.Symbol) return false;
      if (Venue != other.Venue) return false;
      if (!object.Equals(BarSpec, other.BarSpec)) return false;
      if (!object.Equals(Bar, other.Bar)) return false;
      if (IsHistorical != other.IsHistorical) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Symbol.Length != 0) hash ^= Symbol.GetHashCode();
      if (Venue.Length != 0) hash ^= Venue.GetHashCode();
      if (barSpec_ != null) hash ^= BarSpec.GetHashCode();
      if (bar_ != null) hash ^= Bar.GetHashCode();
      if (IsHistorical != false) hash ^= IsHistorical.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Symbol.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Symbol);
      }
      if (Venue.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Venue);
      }
      if (barSpec_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(BarSpec);
      }
      if (bar_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Bar);
      }
      if (IsHistorical != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsHistorical);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Symbol.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Symbol);
      }
      if (Venue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Venue);
      }
      if (barSpec_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BarSpec);
      }
      if (bar_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Bar);
      }
      if (IsHistorical != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BarClosed other) {
      if (other == null) {
        return;
      }
      if (other.Symbol.Length != 0) {
        Symbol = other.Symbol;
      }
      if (other.Venue.Length != 0) {
        Venue = other.Venue;
      }
      if (other.barSpec_ != null) {
        if (barSpec_ == null) {
          barSpec_ = new global::Nautilus.Common.BarSpecification();
        }
        BarSpec.MergeFrom(other.BarSpec);
      }
      if (other.bar_ != null) {
        if (bar_ == null) {
          bar_ = new global::Nautilus.Common.Bar();
        }
        Bar.MergeFrom(other.Bar);
      }
      if (other.IsHistorical != false) {
        IsHistorical = other.IsHistorical;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Symbol = input.ReadString();
            break;
          }
          case 18: {
            Venue = input.ReadString();
            break;
          }
          case 26: {
            if (barSpec_ == null) {
              barSpec_ = new global::Nautilus.Common.BarSpecification();
            }
            input.ReadMessage(barSpec_);
            break;
          }
          case 34: {
            if (bar_ == null) {
              bar_ = new global::Nautilus.Common.Bar();
            }
            input.ReadMessage(bar_);
            break;
          }
          case 40: {
            IsHistorical = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SubscribeTickData : pb::IMessage<SubscribeTickData> {
    private static readonly pb::MessageParser<SubscribeTickData> _parser = new pb::MessageParser<SubscribeTickData>(() => new SubscribeTickData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SubscribeTickData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nautilus.Common.MessagesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubscribeTickData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubscribeTickData(SubscribeTickData other) : this() {
      symbol_ = other.symbol_;
      venue_ = other.venue_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubscribeTickData Clone() {
      return new SubscribeTickData(this);
    }

    /// <summary>Field number for the "symbol" field.</summary>
    public const int SymbolFieldNumber = 1;
    private string symbol_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Symbol {
      get { return symbol_; }
      set {
        symbol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "venue" field.</summary>
    public const int VenueFieldNumber = 2;
    private string venue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Venue {
      get { return venue_; }
      set {
        venue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SubscribeTickData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SubscribeTickData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Symbol != other.Symbol) return false;
      if (Venue != other.Venue) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Symbol.Length != 0) hash ^= Symbol.GetHashCode();
      if (Venue.Length != 0) hash ^= Venue.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Symbol.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Symbol);
      }
      if (Venue.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Venue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Symbol.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Symbol);
      }
      if (Venue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Venue);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SubscribeTickData other) {
      if (other == null) {
        return;
      }
      if (other.Symbol.Length != 0) {
        Symbol = other.Symbol;
      }
      if (other.Venue.Length != 0) {
        Venue = other.Venue;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Symbol = input.ReadString();
            break;
          }
          case 18: {
            Venue = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class UnsubscribeTickData : pb::IMessage<UnsubscribeTickData> {
    private static readonly pb::MessageParser<UnsubscribeTickData> _parser = new pb::MessageParser<UnsubscribeTickData>(() => new UnsubscribeTickData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UnsubscribeTickData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nautilus.Common.MessagesReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnsubscribeTickData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnsubscribeTickData(UnsubscribeTickData other) : this() {
      symbol_ = other.symbol_;
      venue_ = other.venue_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnsubscribeTickData Clone() {
      return new UnsubscribeTickData(this);
    }

    /// <summary>Field number for the "symbol" field.</summary>
    public const int SymbolFieldNumber = 1;
    private string symbol_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Symbol {
      get { return symbol_; }
      set {
        symbol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "venue" field.</summary>
    public const int VenueFieldNumber = 2;
    private string venue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Venue {
      get { return venue_; }
      set {
        venue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UnsubscribeTickData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UnsubscribeTickData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Symbol != other.Symbol) return false;
      if (Venue != other.Venue) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Symbol.Length != 0) hash ^= Symbol.GetHashCode();
      if (Venue.Length != 0) hash ^= Venue.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Symbol.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Symbol);
      }
      if (Venue.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Venue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Symbol.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Symbol);
      }
      if (Venue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Venue);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UnsubscribeTickData other) {
      if (other == null) {
        return;
      }
      if (other.Symbol.Length != 0) {
        Symbol = other.Symbol;
      }
      if (other.Venue.Length != 0) {
        Venue = other.Venue;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Symbol = input.ReadString();
            break;
          }
          case 18: {
            Venue = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SubscribeBarData : pb::IMessage<SubscribeBarData> {
    private static readonly pb::MessageParser<SubscribeBarData> _parser = new pb::MessageParser<SubscribeBarData>(() => new SubscribeBarData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SubscribeBarData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nautilus.Common.MessagesReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubscribeBarData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubscribeBarData(SubscribeBarData other) : this() {
      symbol_ = other.symbol_;
      venue_ = other.venue_;
      barSpec_ = other.barSpec_ != null ? other.barSpec_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubscribeBarData Clone() {
      return new SubscribeBarData(this);
    }

    /// <summary>Field number for the "symbol" field.</summary>
    public const int SymbolFieldNumber = 1;
    private string symbol_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Symbol {
      get { return symbol_; }
      set {
        symbol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "venue" field.</summary>
    public const int VenueFieldNumber = 2;
    private string venue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Venue {
      get { return venue_; }
      set {
        venue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "barSpec" field.</summary>
    public const int BarSpecFieldNumber = 3;
    private global::Nautilus.Common.BarSpecification barSpec_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Nautilus.Common.BarSpecification BarSpec {
      get { return barSpec_; }
      set {
        barSpec_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SubscribeBarData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SubscribeBarData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Symbol != other.Symbol) return false;
      if (Venue != other.Venue) return false;
      if (!object.Equals(BarSpec, other.BarSpec)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Symbol.Length != 0) hash ^= Symbol.GetHashCode();
      if (Venue.Length != 0) hash ^= Venue.GetHashCode();
      if (barSpec_ != null) hash ^= BarSpec.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Symbol.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Symbol);
      }
      if (Venue.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Venue);
      }
      if (barSpec_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(BarSpec);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Symbol.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Symbol);
      }
      if (Venue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Venue);
      }
      if (barSpec_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BarSpec);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SubscribeBarData other) {
      if (other == null) {
        return;
      }
      if (other.Symbol.Length != 0) {
        Symbol = other.Symbol;
      }
      if (other.Venue.Length != 0) {
        Venue = other.Venue;
      }
      if (other.barSpec_ != null) {
        if (barSpec_ == null) {
          barSpec_ = new global::Nautilus.Common.BarSpecification();
        }
        BarSpec.MergeFrom(other.BarSpec);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Symbol = input.ReadString();
            break;
          }
          case 18: {
            Venue = input.ReadString();
            break;
          }
          case 26: {
            if (barSpec_ == null) {
              barSpec_ = new global::Nautilus.Common.BarSpecification();
            }
            input.ReadMessage(barSpec_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class UnsubscribeBarData : pb::IMessage<UnsubscribeBarData> {
    private static readonly pb::MessageParser<UnsubscribeBarData> _parser = new pb::MessageParser<UnsubscribeBarData>(() => new UnsubscribeBarData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UnsubscribeBarData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nautilus.Common.MessagesReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnsubscribeBarData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnsubscribeBarData(UnsubscribeBarData other) : this() {
      symbol_ = other.symbol_;
      venue_ = other.venue_;
      barSpec_ = other.barSpec_ != null ? other.barSpec_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnsubscribeBarData Clone() {
      return new UnsubscribeBarData(this);
    }

    /// <summary>Field number for the "symbol" field.</summary>
    public const int SymbolFieldNumber = 1;
    private string symbol_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Symbol {
      get { return symbol_; }
      set {
        symbol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "venue" field.</summary>
    public const int VenueFieldNumber = 2;
    private string venue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Venue {
      get { return venue_; }
      set {
        venue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "barSpec" field.</summary>
    public const int BarSpecFieldNumber = 3;
    private global::Nautilus.Common.BarSpecification barSpec_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Nautilus.Common.BarSpecification BarSpec {
      get { return barSpec_; }
      set {
        barSpec_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UnsubscribeBarData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UnsubscribeBarData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Symbol != other.Symbol) return false;
      if (Venue != other.Venue) return false;
      if (!object.Equals(BarSpec, other.BarSpec)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Symbol.Length != 0) hash ^= Symbol.GetHashCode();
      if (Venue.Length != 0) hash ^= Venue.GetHashCode();
      if (barSpec_ != null) hash ^= BarSpec.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Symbol.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Symbol);
      }
      if (Venue.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Venue);
      }
      if (barSpec_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(BarSpec);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Symbol.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Symbol);
      }
      if (Venue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Venue);
      }
      if (barSpec_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BarSpec);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UnsubscribeBarData other) {
      if (other == null) {
        return;
      }
      if (other.Symbol.Length != 0) {
        Symbol = other.Symbol;
      }
      if (other.Venue.Length != 0) {
        Venue = other.Venue;
      }
      if (other.barSpec_ != null) {
        if (barSpec_ == null) {
          barSpec_ = new global::Nautilus.Common.BarSpecification();
        }
        BarSpec.MergeFrom(other.BarSpec);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Symbol = input.ReadString();
            break;
          }
          case 18: {
            Venue = input.ReadString();
            break;
          }
          case 26: {
            if (barSpec_ == null) {
              barSpec_ = new global::Nautilus.Common.BarSpecification();
            }
            input.ReadMessage(barSpec_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
