name: build-develop

on:
  push:
    branches: [ develop ]

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: |
          wget http://download.redis.io/redis-stable.tar.gz
          tar xvzf redis-stable.tar.gz
          cd redis-stable
          sudo make
          sudo make install
          cd -
          git clone --recursive https://github.com/RedisTimeSeries/RedisTimeSeries.git
          cd RedisTimeSeries
          sudo make build
          cd -
          redis-server --daemonize yes
          redis-cli MODULE LOAD /home/runner/work/Nautilus/Nautilus/RedisTimeSeries/bin/linux-x64-release/redistimeseries.so

      - name: Test
        run: |
          dotnet restore
          dotnet test Source/Nautilus.TestSuite.UnitTests
          dotnet test Source/Nautilus.TestSuite.IntegrationTests
